### ISSUE TITLE
[Odessa] fix button S

### ISSUE THREAD

**Issue by LASArtem** [LASArtem/TrafficLight#2]
Need to fix pushing button "S"

**Comment by LASArtem** [comment]
implementation is started:
[feature/ignust_fix_button_S](https://github.com/LASArtem/TrafficLight/tree/feature/ignust_fix_button_S)

**Comment by LASArtem** [comment]
Implementation is completed

**Comment by LASArtem** [comment]
[PullRequest](https://github.com/LASArtem/TrafficLight/pull/4) is created

**Comment by Ignust** [comment]
PullRequest was merged
